
# Work in progress.


#name: CI
#
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'extension/**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Begin CI...
#        uses: actions/checkout@v2
#
#      - name: Use Node 14
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14.x
#          registry-url: 'https://registry.npmjs.org'
#
#      - name: Use cached node_modules
#        uses: actions/cache@v2
#        with:
#          path: node_modules
#          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            nodeModules-
#
#      - name: Install dependencies
#        run: yarn install --frozen-lockfile
#        env:
#          CI: true
#
#      - name: Lint
#        run: yarn lint
#        env:
#          CI: true
#
#      - name: Build
#        run: yarn build
#        env:
#          CI: true
#
#      - name: Chrome Extension upload & publish
#        uses: Passiverecords/chrome-extension-upload-action@1.4.1
#        with:
#          refresh-token: